version: "3"

services:
  data-gov-frontend-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: data-gov-frontend-development-img
    volumes:
      - ../..:/app
    ports:
      - "3001:3000"
